</$objtype/mkfile

%.ps:DQ:	%.ms macros.ms
	eval `{doctype macros.ms $stem.ms} | \
	lp -m.9 -dstdout >$target

%.pdf:DQ: %.ps
	cat /sys/doc/docfonts $stem.ps >_$stem.ps
	ps2pdf _$stem.ps $stem.pdf && rm -f _$stem.ps

</sys/src/cmd/mkone
